name: caixa_posto_janjao
description: "Aplicativo profissional de Caixa e Fechamento de Turno do Posto Janjão"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Banco de Dados SQLite Local & Web
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.2+2
  path_provider: ^2.1.3
  path: ^1.9.0
  
  # Formatações Monetárias e Datas (pt_BR)
  intl: any
  
  # Integração Google Drive Webhook
  http: ^1.2.1
  
  # Geração e Impressão de PDF Térmico / A4
  pdf: ^3.10.8
  printing: ^5.13.1
  
  # Compartilhamento (WhatsApp / Sistema)
  share_plus: ^9.0.0
  
  # Preferências Locais (Tema, Máquina Ativa, PIN)
  shared_preferences: ^2.2.3

  # Criptografia e Autenticação SHA-256
  crypto: ^3.0.3

dependency_overrides:
  sqflite_android: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
